### ISSUE TITLE
Reviewing orc/oblrc files

### ISSUE THREAD

**Issue by nschneid** [xiulinyang/relative-amr-eval#1]
(Not looking at train split as it would take a long time)

Reduced object RCs in https://github.com/xiulinyang/relative-amr-eval/blob/main/eud_ewt/eud_ewt_dev/orc.txt:
---------------

https://github.com/xiulinyang/relative-amr-eval/blob/4d7f6db12e3d11804f6d0dea19d92c8ae875df0d/eud_ewt/eud_ewt_dev/orc.txt#L3

"anything they like" is an idiom which expands as: "They can write anything they (would) like (to write __)". An interesting case of ellipsis. I think the proper solution is probably to add an abstract (enhanced-only) node for the implicit "write" and mark "anything" as its object. I can do that in the final version of the data.

https://github.com/xiulinyang/relative-amr-eval/blob/4d7f6db12e3d11804f6d0dea19d92c8ae875df0d/eud_ewt/eud_ewt_dev/orc.txt#L23

Similar—I guess it could be interpreted either as "any name you want" (i.e., you want that name) or "the name you want to pick" (you want to pick that name). Let's leave it alone for simplicity.

The rest look good.

Reduced object RCs in https://github.com/xiulinyang/relative-amr-eval/blob/main/eud_ewt/eud_ewt_test/orc.txt
-----------------

All look good!

Reduced non-core RCs in https://github.com/xiulinyang/relative-amr-eval/blob/main/eud_ewt/eud_ewt_dev/oblrc.txt:
-----------------

https://github.com/xiulinyang/relative-amr-eval/blob/4d7f6db12e3d11804f6d0dea19d92c8ae875df0d/eud_ewt/eud_ewt_dev/oblrc.txt#L5

"the text I was supposed to put up" should be obj

https://github.com/xiulinyang/relative-amr-eval/blob/4d7f6db12e3d11804f6d0dea19d92c8ae875df0d/eud_ewt/eud_ewt_dev/oblrc.txt#L14

"the hype they are told": obj

Reduced non-core RCs in https://github.com/xiulinyang/relative-amr-eval/blob/main/eud_ewt/eud_ewt_test/oblrc.txt:
----------------

https://github.com/xiulinyang/relative-amr-eval/blob/4d7f6db12e3d11804f6d0dea19d92c8ae875df0d/eud_ewt/eud_ewt_test/oblrc.txt#L7

"whatever age you are" is actually a predicate relative right?

https://github.com/xiulinyang/relative-amr-eval/blob/4d7f6db12e3d11804f6d0dea19d92c8ae875df0d/eud_ewt/eud_ewt_test/oblrc.txt#L16

This is ungrammatical, should be "which lasted" (subject relative)

https://github.com/xiulinyang/relative-amr-eval/blob/4d7f6db12e3d11804f6d0dea19d92c8ae875df0d/eud_ewt/eud_ewt_test/oblrc.txt#L18

"the extra mile you went": _go_ + distance is tricky but I think this is an object. At least some people are willing to passivize the idiom ("The extra mile was gone by everyone, to ensure our comfort!")

**Comment by xiulinyang** [comment]
Thanks! I corrected most of them, and as for those I'm not sure about, I have opened an issue in the EWT repository.
