### ISSUE TITLE
Validator error: EUD edges need to be sorted by head index

### ISSUE THREAD

**Issue by nschneid** [xiulinyang/relative-amr-eval#2]
e.g. `14:obl:tmod|5:obl` in the dev set should be `5:obl|14:obl:tmod`

I'll try to fix this with some regexes

**Comment by nschneid** [comment]
The files at https://github.com/UniversalDependencies/UD_English-EWT/commit/f968879443531f21f1c218ae7ef453c51ce3d9bc solve this problem. @xiulinyang could you download them and update the eud_* files here?

**Comment by xiulinyang** [comment]
Thanks! I have downloaded the updated files from the ```reduced-rcs-eud``` branch and uploaded them to this repository.

**Comment by nschneid** [comment]
I think the version you downloaded has other updates too but that's OK I guess. These 3 files weren't used for experiments in the paper were they?

**Comment by xiulinyang** [comment]
No, I only used the examples from the training split.

**Comment by nschneid** [comment]
But did you use [eud_ewt_train.conllu](https://github.com/xiulinyang/relative-amr-eval/blob/main/eud_ewt/eud_ewt_train.conllu) in the experiments?

**Comment by xiulinyang** [comment]
Yes, you are right. The data I used are stored in the ```parsed_result/ewt``` folder.

**Comment by nschneid** [comment]
OK, as long as the eud_* files aren't necessary to replicate the results I think we're good.
